### PR TITLE
Fix/game pause button moves

### LINKED ISSUE #36: Pause button is moving on resume
The pause button position changes on window resize, but also when pausing and resuming the game.

### PR DESCRIPTION
**Pull request by Jonas-C**
Changed pause button so that is set to invisble and disabled on pause, and reversed when resumed

### CODE REVIEW

**Review by Brogzybro — APPROVED** [review]
Good solution, but I think we will have to change how score is displayed and further in game interface later on.

File: core/src/com/gaalf/view/GameView.java [hunk 1]
```diff
@@ -74,7 +66,17 @@ public void changed(ChangeEvent event, Actor actor) {
             }
         });
         levelClearedWindow.add(exitMainMenuButton).width(levelClearedWindow.getWidth() / 2).padBottom(15);
+        levelClearedWindow.row();
 
+        nextLevelButton = new TextButton("Next level", getSkin());
```
Comment (Brogzybro) [inline core/src/com/gaalf/view/GameView.java:71]: maybe out this button above the rest?
